name: ci
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: installer uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Ajouter uv au PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      
      - name: installer les dépendances
        run: uv sync

      - name: executer ruff check
        run: uv run ruff check .

      - name: vérifier le formatage
        run: uv run ruff format --check .

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: installer uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Ajouter uv au PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: installer les dépendances
        run: uv sync

      - name: executer mypy
        run: uv run mypy app/

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: installer uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Ajouter uv au PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: installer les dépendances
        run: uv sync

      - name: Bandit
        run: uv run bandit -r app/

  tests: 
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v6
      - name: installer uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Ajouter uv au PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: installer les dépendances
        run: uv sync

      - name: executer les tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
        run: uv run pytest --cov=app --cov-report=term --cov-report=xml
      
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

  # coverage-report: 
  #   needs: tests
  #   runs-on: ubuntu-latest
  #   steps: 
  #     - uses: actions/checkout@v6
  #     - name: telecharger le rapport de couverture
  #       uses: actions/download-artifact@v5
  #       with:
  #         name: coverage-report
  #     - name: publier le rapport de couverture
  #       uses: codecov/codecov-action@v3
  #       with:
  #         file: coverage.xml
  #         flags: unittests
  #         name: codecov-umbrella
  #         fail_ci_if_error: true

      # - name: publier le rapport de couverture
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     file: coverage.xml
      #     flags: unittests
      #     name: codecov-umbrella
      #     fail_ci_if_error: true
